services:
  backend:
    build:
      context: ./backend
    environment:
      PORT: "4000"
      MAX_FILE_SIZE: "10485760" # 10 MB
      ALLOWED_MIME_TYPES: "image/jpeg,image/png,image/webp,image/avif,image/svg+xml"
      MAX_IMAGE_DIMENSION: "1920" # Maximum width or height in pixels
    ports:
      - "4000:4000"
    volumes:
      - uploads:/app/uploads

  client:
    build:
      context: ./client
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  uploads:
