services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - uploads:/app/uploads

  client:
    build:
      context: ./client
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  uploads:
